### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by 41D5** [netcats/CiscoForwardingPoster#1]
This is really great.  I still need to look more from the technical standpoint.

There are some spelling and English typos.  I could help correct it if you want.  Otherwise, not really sure how to document it.  Here are the ones I saw (corrected):

Management Plane
Static Routes
Access Lists

Control Plane
Unknown of changed src
-Ping, Tracert
-SSH,HTTPS

Forwarding Plane
Ingress Interface
VLAN, ingress port etc. -> egress
LPM -> egress
Egress Interface

I hope this helps.  Please keep going with this project.  I love it.

**Comment by netcats** [comment]
Thank you for the input!

(Control Plane)
"Unknown or changed src" is correct, that is the MAC addr learning mechanism.
- added ECMP to Forwarding Plane
